//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDTI_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gate_In_Out
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Plate_numder { get; set; }
        public string DateTime_IN { get; set; }
        public string DateTime_Out { get; set; }
        public int Vechicletype_ID { get; set; }
        public int FK_Purpose { get; set; }
        public int FK_Item_to_Declare { get; set; }
        public int FK_User { get; set; }
    
        public virtual Item_to_declare Item_to_declare { get; set; }
        public virtual User User { get; set; }
        public virtual Purpose_for_visit Purpose_for_visit { get; set; }
        public virtual Vechicle_Type Vechicle_Type { get; set; }
    }
}
