//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDTI_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VTDI_Gatelog_dbEntities : DbContext
    {
        public VTDI_Gatelog_dbEntities()
            : base("name=VTDI_Gatelog_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gate_In_Out> Gate_In_Out { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Item_to_declare> Item_to_declare { get; set; }
        public virtual DbSet<Purpose_for_visit> Purpose_for_visit { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vechicle_Type> Vechicle_Type { get; set; }
    }
}
